### ISSUE TITLE
Views integrate poorly with new version of django-rest-swagger

### ISSUE THREAD

**Issue by szopu** [szopu/django-rest-registration#8]
The schema of the view cannot be seen on the swagger page. This problem was mentioned in issue #7 .

**Comment by polinom** [comment]
So just to recap here.  because we are using function base views and those are turned in to `ApiView` Django rest swagger cant pickup all the info (fields and it's types) because `ApiView` is not aware about `serializer_class`, this attribute is present in `GenericAPIView ` from where all generic views are being subclasses. 

`django-rest-swagger` relies on schema generation process, and schema is auto generated taking info from serializers.  

Here is peace of docs from DRF docs:

> Note: For basic APIView subclasses, default introspection is essentially limited to the URL kwarg path parameters. For GenericAPIView subclasses, which includes all the provided class based views, AutoSchema will attempt to introspect serialiser, pagination and filter fields, as well as provide richer path field descriptions. (The key hooks here are the relevant GenericAPIView attributes and methods: get_serializer, pagination_class, filter_backends and so on.)

http://www.django-rest-framework.org/api-guide/schemas/#per-view-schema-customisation

**Comment by szopu** [comment]
To be precise, for some of the views the schema can't access the serializer info even when the `get_serializer_class` method of the internal view class is replaced via the `serializer_class_getter` decorator.

In other cases the info about serializer is passed via YAML config in the docstring, which does not seem to work in newer `django-rest-swagger` versions.

**Comment by szopu** [comment]
It looks that `APIView` does not have `get_serializer` method which is used by `AutoSchema`. I started providing it in the wrapped api view class and it seems to work. I will release the fix in the next version (0.3.7).
